Fix build on i386
After updating to 2.5.77, the build was failing on i386 with:

/wrkdirs/usr/ports/biology/hyphy/work/hyphy-2.5.77/src/core/global_things.cpp:176:62: error: conversion from 'size_t' (aka 'unsigned int') to 'const _String' is ambiguous
  176 |     HandleApplicationError(_String("Failed to allocate '") & bytes & "' bytes'",
      |                                                              ^~~~~

Fix the build by explicitly casting size_t variables to unsigned long
when passing them to _String constructors.  _String has multiple
constructors accepting numeric types (long, unsigned long, hyFloat,
char), but not directly a size_t.